### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by zachsai** [genandnic/Wall-Jump#29]
https://pastebin.com/Je0bw9zA
1.16.5
Forge: 36.0.1
1.3.6 Wall Jump

**Comment by FuryOfFools** [comment]
I got this problem too
[crash-2021-01-20_03.31.18-client.txt](https://github.com/genandnic/Wall-Jump/files/5839364/crash-2021-01-20_03.31.18-client.txt)
1.16.4 
Forge: 35.1.37
1.3.6 Wall Jump

**Comment by mrgamer915** [comment]
Made an account specifically for this, the latest version of forge, that being 35.1.37, crashes shortly after joining a minecraft world. Several of my friends crashed repeatedly shortly after join once they updated their version of forge. Tested this myself, here's the crash report:
[crash-2021-01-20_20.57.45-client.txt](https://github.com/genandnic/Wall-Jump/files/5846788/crash-2021-01-20_20.57.45-client.txt)

**Comment by SaitoPhoenix** [comment]
I can confirm the problem as well.  The crash occurred on Forge 35.1.37, but I also tested it on 35.1.34 and there were no issues.

MC: 1.16.4
Forge: 35.1.37
WallJump: 1.3.6
https://pastebin.com/KVLCLJx1
